package genfiles_test

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/truvity/pulumi-pipeline/pkg/genfiles"
)

func vetoPromoted(p string) bool { return filepath.Base(p) == "keep.yaml" }

var owner = genfiles.Owner{Patterns: []string{"out/*.yaml"}, Exclude: vetoPromoted}

func put(t *testing.T, root, rel, content string) {
	t.Helper()
	require.NoError(t, os.MkdirAll(filepath.Dir(filepath.Join(root, rel)), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(root, rel), []byte(content), 0o644))
}

func TestDiffApply(t *testing.T) {
	root := t.TempDir()
	put(t, root, "out/same.yaml", "same")
	put(t, root, "out/edited.yaml", "hand edit")
	put(t, root, "out/stale.yaml", "stale")
	put(t, root, "out/keep.yaml", "other tool's")
	put(t, root, "elsewhere/unowned.yaml", "x")

	desired := []genfiles.File{
		{Path: "out/same.yaml", Content: []byte("same")},
		{Path: "out/edited.yaml", Content: []byte("generated")},
		{Path: "out/new.yaml", Content: []byte("new")},
	}

	res, err := genfiles.Diff(root, desired, owner)
	require.NoError(t, err)
	assert.Equal(t, []string{"out/new.yaml"}, res.Created)
	assert.Equal(t, []string{"out/edited.yaml"}, res.Updated)
	assert.Equal(t, []string{"out/stale.yaml"}, res.Deleted)
	assert.Equal(t, []string{"out/same.yaml"}, res.Skipped)

	// Diff writes nothing.
	b, _ := os.ReadFile(filepath.Join(root, "out/edited.yaml"))
	assert.Equal(t, "hand edit", string(b))

	require.NoError(t, genfiles.Apply(root, desired, res))

	for p, want := range map[string]string{"out/edited.yaml": "generated", "out/new.yaml": "new", "out/keep.yaml": "other tool's"} {
		b, err := os.ReadFile(filepath.Join(root, p))
		require.NoError(t, err)
		assert.Equal(t, want, string(b), p)
	}

	assert.NoFileExists(t, filepath.Join(root, "out/stale.yaml"))
	assert.FileExists(t, filepath.Join(root, "elsewhere/unowned.yaml"))

	again, err := genfiles.Diff(root, desired, owner)
	require.NoError(t, err)
	assert.Empty(t, again.Created)
	assert.Empty(t, again.Updated)
	assert.Empty(t, again.Deleted)

	// No temp file is left behind.
	m, _ := filepath.Glob(filepath.Join(root, "out", "*"+genfiles.TempSuffix))
	assert.Empty(t, m)
}

func TestWriteSkipsIdenticalContent(t *testing.T) {
	root := t.TempDir()

	changed, err := genfiles.Write(root, "cfg", "gen/a/b.yaml", []byte("x: 1\n"))
	require.NoError(t, err)
	assert.True(t, changed)

	changed, err = genfiles.Write(root, "cfg", "gen/a/b.yaml", []byte("x: 1\n"))
	require.NoError(t, err)
	assert.False(t, changed)

	require.NoError(t, genfiles.Remove(root, "cfg", "gen/a/b.yaml"))
	require.NoError(t, genfiles.Remove(root, "cfg", "gen/a/b.yaml"), "removing a missing file is fine")
}

// Every write under gen/ carries a provenance stamp.
func TestEnsureStamp(t *testing.T) {
	t.Run("gen path gets a path-derived stamp", func(t *testing.T) {
		out := genfiles.EnsureStamp("gen/kernel/vpc.yaml", []byte("a: 1\n"))
		assert.Equal(t, "# GENERATED by pulumi stack vpc (kernel account) — do not edit manually.\n", string(out[:bytes.IndexByte(out, '\n')+1]))
		assert.Contains(t, string(out), "a: 1")
	})

	t.Run("existing stamp is not duplicated", func(t *testing.T) {
		in := []byte("# GENERATED by something explicit — do not edit manually.\na: 1\n")
		assert.Equal(t, in, genfiles.EnsureStamp("gen/kernel/vpc.yaml", in))
	})

	t.Run("non-gen path untouched", func(t *testing.T) {
		in := []byte("roles:\n")
		assert.Equal(t, in, genfiles.EnsureStamp("access.yaml", in))
	})
}
